### ISSUE TITLE
package review

### ISSUE THREAD

**Issue by kasperdanielhansen** [hansenlab/yamss#9]
Current status
- [X] Move limma to imports.
- [x] Add unit tests
- [X] "Many functions that you're writing include stopifnot(myclass). Perhaps you intend to write methods that dispatch on your class".  We will not do this.
- [x] Nesting of lapply, sapply - It is not good for readability, and may be avoidable. Perhaps you can pass additional arguments to the first lapply call (i.e., lapply(seq_along(object), function (i, newObj) { ... }, newObj = object))
- [x] Try to avoid call sequences such as rbind > lapply > cbind > rbind > lapply > cbind.
- [x] Use of 1:length(number) is not robust when the number variable is 0L. Try using seq_len(number) instead.
- [x] Minor: Avoid using ifelse for scalar evaluation, just use if ( ) else ( )
- [x] You shouldn't be using @ to access slots in your class. Please use accessors and replacers for this.
- [x] Avoid using argument names that are functions such as by.
- [X] You include an example with \dontrun. It looks runnable.

Additional issues
- [ ] Use minScan in backgroundCorrection.
- [ ] Use minScan in rtAlignment.
- [x] Either make slicepi work on cmsRawExample or figure out a useful cutoff to use.
- [x] Make sure no warnings in bakedpi
- [x] Add tests for slicepi
- [x] Compress cmsRawExample using save(..., compress = "xz")
- [x] Remove the vignette data from data
- [x] Go through the examples and make sure the ones we can update to use cmsRawExample, does this. What we can do here, is include a small runnable example and then a bigger (more realistic) \dontrun{} example

**Comment by onursenol** [comment]
I am new at R project. Where can i get a tutorial  to use yamms, data optimizing so on. I have lots of metabolomics data and need to  evaluate them. I am so new and dont have any tutorial book etc.

**Comment by lmyint** [comment]
Hi,
Please look at our [vignette](https://bioconductor.org/packages/release/bioc/vignettes/yamss/inst/doc/yamss.html) at our [Bioconductor page](https://bioconductor.org/packages/release/bioc/html/yamss.html). If you are completely new to R, I recommend this [R Programming Coursera class](https://www.coursera.org/learn/r-programming).
